title: Coddiwomple
description: |
  I travel. You Read.
permalink: ':title/'
baseurl: "/coddiwomple" # the subpath of your site, e.g. /blog
baseimgurl: "/coddiwomple/assets/img"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/New_York

# Author Settings
author: Jacky Reif
author-img: joshua_tree.jpg
about-author:
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
sass:
  sass_dir: assets/css/scss

paginate: 7
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
